### ISSUE TITLE
remote video not loading (ios and android), twilio console shows devices are connected.

### ISSUE THREAD

**Issue by lonemanotzi** [armackey/nativescript-twilio-video#16]
I am  trying to use this plugin to create an app to video chat.
1. node server is up and running and ngrock is pointing to the node server.
2. One page native script angular app, home component code is copied from the demo app. (demo app no longer working with tns 6.1/ng8.0
3. twilio console is showing the room connected for peer-to-peer
(Twilio log)
22:17:45 CST 2020-01-16 | roomRMbc17902963410b599f8fbc41ef15a80b | peer-to-peer | 26 secs | TURN
4. device 1 (emulator) Connect button click shows tns console > com.twilio.video.Room@8c590
5. device 2 (physical device) Connect button click shows tns console > com.twilio.video.Room@7805405
6. no remote video on both devices. Local video is working on both devices
7.Disconnect button click throws an error (both devices)> ERROR TypeError: this.room.disconnect is not a function
`ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 403328001,
JS:       "rootNodeFlags": 402653185,
JS:       "nodeMatchedQueries": 6,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": -1,
JS:           "flags": 402653184,
JS:           "childFlags": 0,
JS:           "directChildFlags": 0,
JS:           "childMatchedQueries": 0,
JS:           "ngContentIndex": -1,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "childCount": 0,
JS:           "bindings": [],
JS:           "bindingFlags": 0,
JS:           "outputs": [],
JS:           "element": null,
JS:           "provider": null,
JS:           "text": null,
JS:           "query": {
JS:             "id": 1,
JS:             "filterId": 2,
JS:             "bindings": [
JS:               {
JS:                 "propName": "localvideo",
JS:                 "bindingType": 0
JS:               }
JS:             ]
JS:           },
JS:          ...`

***********
Package.json file
*********
{
  "name": "vt",
  "nativescript": {
    "id": "org.nativescript.vt",
    "tns-android": {
      "version": "6.1.2"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle",
    "mobile": "tns run --bundle",
    "preview": "tns preview --bundle"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "core-js": "^2.5.4",
    "nativescript-angular": "8.0.2",
    "nativescript-permissions": "^1.3.8",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-twilio-video": "^1.1.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.3.3",
    "tns-core-modules": "6.0.1",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.22",
    "@angular/cli": "^7.2.0",
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "~0.4.0",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nativescript-dev-webpack": "1.0.1",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "3.4.5"
  }
}

Any help would be greatly appreciated. Twilio support is asking to give console log, but nothing is reporting in console log other than what is mentioned above.

**Comment by armackey** [comment]
If I have some free time over the weekend I'll look into this.

**Comment by lonemanotzi** [comment]
I really appreciate you replying to this email
Recent twilio change is forcing is to use minsdk24, so the issue cod be
there too.

Thanks
John

**Comment by armackey** [comment]
@lonemanotzi 
just re-read your issue. this will never work on an emulator. emulators do not have a camera nor a microphone. please try again on two physical devices.

**Comment by lonemanotzi** [comment]
I tried on two actual devices too (Android and iOS), on both devices I can
see the local video. Clicking connect will not show remote video (however
twilio shows room was connected)

**Comment by armackey** [comment]
ha well this is embarrassing.. i can't even get local video going.. i opened a [ticket](https://github.com/armackey/nativescript-twilio-video/issues/17) for myself.

**Comment by ghost** [comment]
Have you had a chance to look at this? I was able to use the plugin successfully on an IPhone 7 and saw both the local and remote videos but on a Samsung Note 10 I was only able to see my local video. I couldn't see the remote video. The audio worked fine on both devices.
